//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDb2Entities : DbContext
    {
        public TestDb2Entities()
            : base("name=TestDb2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<tblManagerMap> tblManagerMaps { get; set; }
        public virtual DbSet<FinalView> FinalViews { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<View_2> View_2 { get; set; }
    }
}
